<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'name' => 'Theme Dynamic',
    'package' => 'dynamic',
    'version' => '2.3.10-5',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/dynamic',
  ),
  2 => 
  array (
    'package' => 'Slim',
    'name' => 'Slim',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/Slim',
    'active' => 1,
  ),
  3 => 
  array (
    'package' => 'kvcodes',
    'name' => 'kvcodes',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/kvcodes',
    'active' => 0,
  ),
  4 => 
  array (
    'package' => 'api',
    'name' => 'api',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/api',
    'active' => 1,
  ),
  5 => 
  array (
    'name' => 'Sales Summary Report',
    'package' => 'rep_sales_summary',
    'version' => '2.3.3-3',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/rep_sales_summary',
  ),
  6 => 
  array (
    'name' => 'Report Generator',
    'package' => 'repgen',
    'version' => '2.3.9-4',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/repgen',
  ),
  7 => 
  array (
    'name' => 'Theme Modern',
    'package' => 'modern',
    'version' => '2.3.0-6',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/modern',
  ),
  8 => 
  array (
    'name' => 'Theme Anterp',
    'package' => 'anterp',
    'version' => '2.3.0-5',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/anterp',
  ),
);
?>